import 'package:get/get.dart';
import 'package:live_yoko/Utils/Utils.dart';

class TextByNation {
  static RxString nationCode = 'en'.obs;

  static String getStringByKey(String key) {
    if (nationCode.value == 'vi') {
      return vietnam[key] ?? 'Chưa định nghĩa';
    } else if (nationCode.value == 'en') {
      return english[key] ?? 'No define';
    }
    return chinese[key] ?? '未定义';
  }

  static Map vietnam = {
    'username': 'Tên người dùng',
    'password': 'Mật khẩu',
    'welcome': 'Chào mừng đến với ChatAPP',
    'login_content':
        'Đăng nhập ngay để khám phá tính năng và kết nối với bạn bè.',
    'forgotpass': 'Quên mật khẩu?',
    'login_error': 'Lỗi đăng nhập',
    'login': 'Đăng nhập', //đăng nhập
    'chatApp': 'ChatApp',
    'my_account': 'Tài khoản của tôi',
    'friend': 'Bạn bè',
    'Invite_friend': 'Yêu cầu kết bạn',
    'night_mode': 'Chế độ ban đêm',
    'chat_setting': 'Cài đặt trò chuyện',
    'notification': 'Thông báo',
    'language': 'Ngôn ngữ',
    'log_out': 'Đăng xuất',
    'welcome_chat': 'Chào mừng đến với ChatApp',
    'welcome_content':
        'Ứng dụng nhắn tin giúp bạn bảo vệ quyền riêng tư của mình với bạn bè và tổ chức. Bắt đầu cuộc trò chuyện với bạn bè và tổ chức của bạn.',
    'create_chat': 'Tạo cuộc trò chuyện',
    'pin': 'Ghim',
    'delete_chat': 'Xóa cuộc trò chuyện',
    'selct_chat': 'Chọn nhiều cuộc trò chuyện',
    'cancel': 'Hủy bỏ',
    'delete': 'Xóa',
    'light_mode': 'Chế độ sáng',
    'dark_mode': 'Chế độ tối',
    'auto_mode': 'Chế độ Tự động',
    'select': 'Đã chọn',
    'account': 'Tài khoản',
    'settings': 'Cài đặt',
    'chat_delete': 'Xóa vĩnh viễn cuộc trò chuyện với', // trò chuyện
    'search_chat': 'Tìm kiếm trò chuyện, nhóm',
    'recent': 'GẦN ĐÂY',
    'clear': 'Xóa', // tìm kiếm trò chuyện
    'new_group': 'Nhóm mới',
    'friends': 'Bạn bè', // tạo cuộc trò chuyện
    'choose_member': 'Chọn thành viên',
    'auto_delete_chat': 'Tự động Xóa Tin nhắn',
    'off': 'Tắt',
    'auto_delete_chat_content':
        'Tự động xóa tin nhắn trong nhóm này cho tất cả mọi người sau một khoảng thời gian',
    'members': 'Thành viên',
    'create': 'Tạo',
    'auto_delete_title': 'Tự động xóa tin nhắn',
    'auto_delete_content': 'Tự động xóa được kích hoạt để thuận tiện cho bạn',
    'day': 'ngày',
    'days': 'ngày', // tạo nhóm
    'update_profile': 'Cập nhật hồ sơ',
    'update_profile_content':
        'Cập nhật hồ sơ giúp bạn bè dễ nhận diện bạn hơn.',
    'person_information': 'Thông tin cá nhân',
    'first_name': 'Tên Đầy Đủ',
    'last_name': 'Họ',
    'update': 'Cập nhật', // cập nhật hồ sơ
    'search_friend': 'Tìm kiếm bạn bè',
    'received': 'Đã nhận',
    'sent': 'ĐÃ GỬI',
    'accept': 'Chấp nhận',
    'prieview': 'xem trước',
    'mesage_text_size': 'Kích thước văn bản tin nhắn',
    'color_theme': 'Chủ đề màu sắc', // cài đặt trò chuyện
    'chat_notification': 'Thông báo trò chuyện',
    'notification_content': 'Nhận thông báo đẩy khi có thông báo mới',
    'translate_mesages': 'Dịch tin nhắn',
    'translate_content': 'Chọn ngôn ngữ bạn muốn dịch tin nhắn sang',
    'laguage_systems': 'Hệ thống ngôn ngữ',
    'language_translate': 'Dịch ngôn ngữ',
    'language_conttent':
        'Chọn ngôn ngữ bạn muốn dịch tin nhắn sang', // ngôn ngữ
    'type_a_message': 'Nhập tin nhắn...',
    'no_message': 'Không có tin nhắn nào trong cuộc trò chuyện.',
    'media': 'Hình ảnh và video',
    'sharelink': 'Chia sẻ liên kết',
    'document': 'Tài liệu',
    'atuto_delete': 'Tự động Xóa',
    'clear_history': 'Xóa lịch sử',
    'leave_group': 'Rời khỏi nhóm',
    'reply': 'Trả lời',
    'copy': 'Sao chép',
    'forward': 'Chuyển tiếp',
    'recall': 'Nhắc lại',
    'edit': 'Chỉnh sửa',
    'multiple_select': 'Chọn nhiều',
    'error_name': 'Tên không được để trống', //error
    'error_message': 'Thông báo lỗi danh sách tin nhắn',
    'error_file': 'Thông báo lỗi file',
    'error_delete_message': 'Thông báo lỗi xóa tin nhắn',
    'error_login': 'Thông báo lỗi đăng nhập',
    'file_notification': 'Thông báo file',
    'error_image_video': 'Chỉ thêm được ảnh hoặc video riêng biệt',
    'error_update': 'Chỉ thêm được 1 video',
    'add_friend_ss': 'Đã trở thành bạn bè với!',
    'no_add_friend': 'Đã từ chối kết bạn với!',
    'no_access': 'Không có quyền truy cập',
    'video': 'Video',
    'image': 'Hình ảnh',
    'file': 'Tệp',
    'audio': 'Âm thanh',
    'enter_message': 'Nhập tin nhắn',
    'downloading': ' Đang tải xuống...',
    'choose_mode': 'Chọn chế độ giao diện phù hợp với bạn',
    'delete_message': 'Đã xóa đoạn chat!',
    'group_name': 'Tên nhóm',
    'error_api_no_connect':
        'Không kết nối được đến máy chủ, bạn vui lòng kiểm tra lại.',
    'unlock_friend': 'Mở khóa gửi\nlời mời kết bạn',
    'translater': 'Dịch',
    'admin_create': 'Đã tạo nhóm',
    'cancel_friend': 'Hủy kết bạn',
    'cancal_friend_with': 'Hủy kết bạn với',
    'cancal_friend_ss': 'Đã hủy kết bạn',
    'add_friend': 'Thêm bạn',
    'leader': 'Trưởng nhóm',
    'add_member': 'Thêm thành viên',
    'friend_sent': 'Đã gửi lời mời kết bạn',
    'me': 'Tôi',
    'confirm': 'Xác nhận',
    'delete_group': 'Xóa nhóm',
    'leave_group_confirm':
        'Bạn có chắc chắn muốn rời khỏi và xóa cuộc trò chuyện nhóm này từ phía bạn không?',
    'delete_group_confirm':
        'Bạn có chắc chắn muốn xóa cuộc trò chuyện nhóm này không?',
    'add_account': 'Thêm Tài khoản',
    'you_sure_loguot': 'Bạn chắc chắn muốn đăng xuất chứ?',
    'Email': 'Email',
    'admin': 'Quản trị viên',
    'user': 'Người dùng',
    'user_name_empty': 'User name không được để trống',
    'email_empty': 'Email không được để trống',
    'last_name_empty': 'Họ không được để trống',
    'name_empty': 'Tên không được để trống',
    'detail': 'Chi tiết',
    'select_filter': 'Chọn chức danh công việc bạn muốn lọc',
    'status': 'Trạng thái',
    'status_active': 'Đang hoạt động',
    'status_deactive': 'Đã khóa',
    'list_account': 'Danh sách tài khoản',
    'account_detail': 'Chi tiết tài khoản',
    'email_format': 'Email không đúng định dạng',
    'permission_successfully': 'Thay đổi quyền thành công',
    'status_successfully': 'Thay đổi trạng thái thành công',
    'lock_account': 'Khóa tài khoản',
    'unlock_account': 'Mở khóa tài khoản',
    'position': 'Vị trí',
    'change_pass': 'Đổi mật khẩu',
    'pass_old': 'Nhập mật khẩu cũ',
    'pass_new': 'Nhập mật khẩu mới',
    'pass_new_en': 'Nhập lại mật khẩu mới',
    'pass_validate': 'Mật khẩu phải có ít nhất 8 ký tự!',
    'pass_ss': 'Đổi mật khẩu thành công!',
    'pass_valiate_distinctive': 'Mật khẩu mới phải khác mật khẩu cũ!',
    'pass_valiate_overlap': 'Nhập lại mật khẩu chưa khớp với mật khẩu mới!',
    'name_ss': 'Cập nhật thành công!',
    'download': 'Tải xuống',
    'photo_saved_successfully': 'Ảnh đã được lưu vào thư viện ảnh thành công!',
    'photo_saved_error': 'Đã có lỗi xảy ra khi lưu ảnh vào thư viện ảnh.',
    'cancel_friend_send': 'Đã hủy lời mời kết bạn với',
    'is_typing': 'đang gõ',
    'file_size': 'Kích thước tệp vượt quá 20 MB',
    'un_pin': 'Bỏ gim',
    'search': 'Tìm kiếm',
    'search_nation': 'Nhập tên hoặc mã quốc gia',
    'pinned_message': 'Tin nhắn đã ghim',
    'pin_list': 'Danh sách ghim',
    'by': 'Bởi',
    'back_login': 'Quay lại đăng nhập',
    'dont_account': 'Bạn chưa có tài khoản? ',
    'sign_up_here': 'Đăng ký tại đây',
    'sign_up': 'Đăng ký',
    'we_code_phone': 'Chúng tôi đã gửi cho bạn mã số điện thoại',
    'otp': 'OTP',
    'information_join': 'Điền đầy đủ thông tin để tham gia cùng chúng tôi',
    'full_name': 'Tên đầy đủ',
    'enter_password': 'Nhập lại mật khẩu',
    'phone_number': 'Số điện thoại',
    'continue': 'Tiếp tục',
    'phone_empty': 'Số điện thoại không được để trống',
    'password_empty': 'Mật khẩu không được để trống',
    'confirm_password_empty': 'Xác nhận mật khẩu không được để trống',
    'phone_format': 'Số điện thoại không đúng định dạng',
    'auto_delete': 'Xóa tự động',
    'otp_no_valid': 'otp không hợp lệ',
    'enter_otp': 'Nhập otp',
    'phone_no_valid': 'Số điện thoại không hợp lệ!',
    'forgot_pass': 'Quên mật khẩu?',
    'forgot_pass_ct':
        'Chúng tôi sẽ gửi cho bạn một liên kết đến địa chỉ số điện thoại bạn đã cung cấp trước đó.',
    'forgot_pas_phone': 'Chúng tôi đã gửi cho bạn mã tới số điện thoại',
    'phone': 'Số điện thoại',
    'phone_null': 'Vui lòng nhập số điện thoại',
    'phone_valid': 'Số điện thoại không hợp lệ',
    'pass_null': 'Vui lòng nhập mật khẩu!',
    'pass_re_null': 'Vui lòng nhập lại mật khẩu!',
    'pass_reset_ss': 'Lấy lại mật khẩu thành công!',
    'resgiter_ss': 'Đăng ký tài khoản thành công!',
    'pass_no_joint': 'Nhập lại mật khẩu chưa trùng khớp!',
    'last_seen': 'Xem lần cuối',
    'send': 'Gửi',
    'forward_from': 'Chuyển tiếp từ',
    'edited': 'đã chỉnh sửa',
    'reset_pass': 'Đặt lại mật khẩu',
    'reset_pass_ss': 'đã đặt mật khẩu thành 123',
    'file_not_supported': 'File không hỗ trợ',
    'only_photo_video_file':
        'Chỉ thêm được ảnh hoặc video hoặc file riêng biệt',
    'only_video': 'Chỉ thêm được 1 video',
    'only_file': 'Chỉ thêm được 1 file',
    'message_been_deleted': 'Tin nhắn đã bị xóa',
    'back_lg': 'Tài khoản đã đăng nhập ở thiết bị khác',
    'clear_history_confirm':
        'Bạn có chắc chắn muốn xóa lịch sử cuộc trò chuyện này không?',
    'reset_password_confirm':
        'Bạn có chắc chắn muốn đặt lại mật khẩu này không?',
    'unable_send': 'Không thể gửi',
  };

  static Map english = {
    'username': 'Username',
    'password': 'Password',
    'welcome': 'Welcome to ChatApp',
    'login_content': 'Log in now to explore features and connect with friends.',
    'forgotpass': 'Forgot password?',
    'login_error': 'Login Error',
    'login': 'Login', //login
    'chatApp': 'ChatApp',
    'my_account': 'My Account',
    'friend': 'Friends',
    'Invite_friend': 'Friend request',
    'night_mode': 'Night Mode',
    'chat_setting': 'Chat Settings',
    'notification': 'Notifications',
    'language': 'Language',
    'log_out': 'Log out',
    'welcome_chat': 'Welcome to ChatApp',
    'welcome_content':
        'The messaging app helps you keep your privacy rights with friends and organizations. Start conversations with your friends and organizations.',
    'create_chat': 'Create a Chat',
    'pin': 'Pin',
    'delete_chat': 'Delete Chat',
    'selct_chat': 'Select Multiple Chats',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'light_mode': 'Light Mode',
    'dark_mode': 'Dark Mode',
    'auto_mode': 'Auto - Mode',
    'select': 'Selected',
    'account': 'Account',
    'settings': 'Settings',
    'chat_delete': 'Permanently delete chat with', // chat
    'search_chat': 'Search for chat, group',
    'recent': 'RECENT',
    'clear': 'Clear', // search chat
    'new_group': 'New group',
    'friends': 'Friends', // create chat
    'choose_member': 'Choose Member',
    'auto_delete_chat': 'Auto-Delete Messages',
    'off': 'Off',
    'auto_delete_chat_content':
        'Automatically delete messages in this group for everyone after a period of time',
    'members': 'Members',
    'create': 'Create',
    'auto_delete_title': 'Automatically delete messages',
    'auto_delete_content': 'Auto-delete engaged for your convenience',
    'day': 'day',
    'days': 'days', // create group
    'update_profile': 'Update profile',
    'update_profile_content':
        'Updating your profile makes it easier for friends to recognize you.',
    'person_information': 'Person Information',
    'first_name': 'Full name',
    'last_name': 'Last name',
    'update': 'Update', // update profile
    'search_friend': 'Looking for friends',
    'received': 'Received',
    'sent': 'SENT',
    'accept': 'Accept',
    'prieview': 'prieview',
    'mesage_text_size': 'Mesage text size',
    'color_theme': 'Color theme', // chat setting
    'chat_notification': 'Chat notifications',
    'notification_content':
        'Receive push notifications when there are new announcements',
    'translate_mesages': 'Translate message',
    'translate_content':
        'Select the message language you want to translate into',
    'laguage_systems': 'laguage systems',
    'language_translate': 'Language translate',
    'language_conttent':
        'Select the message language you want to translate into', //language
    'type_a_message': 'Type a message...',
    'no_message': 'There are no messages in the conversation.',
    'media': 'Media',
    'sharelink': 'Share link',
    'document': 'Documents',
    'atuto_delete': 'Auto-Delete',
    'clear_history': 'Clear history',
    'leave_group': 'Leave-Group',
    'reply': 'Reply',
    'copy': 'Copy',
    'forward': 'Forward',
    'recall': 'Recall',
    'edit': 'Edit',
    'multiple_select': 'Multiple select',
    'error_name': 'Name must not be empty',
    'error_message': 'Message list error notification',
    'error_file': 'File error notification',
    'error_delete_message': 'Delete message error notification',
    'error_login': 'Login error notification',
    'file_notification': 'File notification',
    'error_image_video': 'Only add separate images or videos',
    'error_update': 'Only 1 video can be added',
    'add_friend_ss': 'Has become friends with!',
    'no_add_friend': 'Friend request rejected!',
    'no_access': 'No access',
    'video': 'Video',
    'image': 'Image',
    'file': 'File',
    'audio': 'Audio',
    'enter_message': 'Enter a message',
    'downloading': 'Downloading...',
    'choose_mode': 'Choose a mode that suits you',
    'delete_message': 'Message deleted!',
    'group_name': 'Group Name',
    'error_api_no_connect': 'Can t connect to the server, please check again.',
    'unlock_friend': 'Unlock sending\nfriend requests',
    'translater': 'Translate',
    'admin_create': 'has created group',
    'cancel_friend': 'Unfriend',
    'cancal_friend_with': 'Cancel friend request with',
    'cancal_friend_ss': 'Friend request canceled',
    'add_friend': 'Add friend',
    'leader': 'Group leader',
    'add_member': 'Add member',
    'friend_sent': 'Friend request sent',
    'me': 'Me',
    'confirm': 'Confirm',
    'delete_group': 'Delete group',
    'leave_group_confirm':
        'Are you sure you want to leave and delete this group chat?',
    'delete_group_confirm': 'Are you sure you want to delete this group chat?',
    'add_account': 'Add Account',
    'you_sure_loguot': 'Are you sure you want to sign out?',
    'email': 'Email',
    'admin': 'Admin',
    'user': 'User',
    'user_name_empty': 'User name cannot be empty',
    'email_empty': 'Email cannot be empty',
    'last_name_empty': 'Last name cannot be empty',
    'name_empty': 'Name cannot be empty',
    'detail': 'Detail',
    'position': 'Position',
    'select_filter': 'Select the job title you want to filter',
    'status': 'Status',
    'status_active': 'Active',
    'status_deactive': 'Deactivated',
    'list_account': 'Account list',
    "account_detail": "Account detail",
    'email_format': 'Email is not in the correct format',
    'permission_successfully': 'Permission changed successfully',
    'status_successfully': 'Status change successfully',
    'lock_account': 'Lock account',
    'unlock_account': 'Unlock account',
    'change_pass': 'Change password',
    'pass_old': 'Enter old password',
    'pass_new': 'Enter new password',
    'pass_new_en': 'Re-enter new password',
    'pass_validate': 'Password must be at least 8 characters long!',
    'pass_ss': 'Password changed successfully!',
    'pass_valiate_distinctive':
        'New password must be different from old password!',
    'pass_valiate_overlap':
        'Re-entered password does not match the new password!',
    'name_ss': 'Update successful!',
    'download': 'Download',
    'photo_saved_successfully':
        'Photo has been saved to the camera roll successfully!',
    'photo_saved_error':
        'An error occurred while saving a photo to your photo library.',
    'cancel_friend_send': 'Cancelled friend request',
    'is_typing': 'is typing',
    'file_size': 'File size exceeds 20MB',
    'un_pin': 'Unpin',
    'search': 'Search',
    'search_nation': 'Enter the name or country code',
    'pinned_message': 'Pinned message',
    'pin_list': 'Pin list',
    'by': 'By',
    'back_login': 'Back to login',
    'dont_account': 'Don’t have an account? ',
    'sign_up_here': 'Sign up here',
    'sign_up': 'Sign up',
    'we_code_phone': 'We have sent you a code to phone number',
    'otp': 'OTP',
    'information_join': 'Fill in all information to join us',
    'full_name': 'Full name',
    'enter_password': 'Enter password again',
    'phone_number': 'Phone number',
    'continue': 'Continue',
    'phone_empty': 'Phone number cannot be empty',
    'password_empty': 'Password cannot be empty',
    'confirm_password_empty': 'Confirm password cannot be empty',
    'phone_format': 'Phone number is not in the correct format',
    'auto_delete': 'Automatic deletion',
    'otp_no_valid': 'Invalid OTP',
    'enter_otp': 'Enter OTP',
    'phone_no_valid': 'Invalid phone number!',
    'forgot_pass': 'Forgot password?',
    'forgot_pass_ct':
        'We will send you a link to the phone number you provided earlier.',
    'forgot_pas_phone': 'We have sent a code to the phone number',
    'phone': 'Phone number',
    'phone_null': 'Please enter your phone number',
    'phone_valid': 'Invalid phone number',
    'pass_null': 'Please enter your password!',
    'pass_re_null': 'Please re-enter your password!',
    'pass_reset_ss': 'Password reset successful!',
    'resgiter_ss': 'Account registration successful!',
    'pass_no_joint': 'Re-entered password does not match!',
    'last_seen': 'Last seen',
    'send': 'Send',
    'forward_from': 'Forward from',
    'edited': 'edited',
    'reset_pass': 'Reset password',
    'reset_pass_ss': 'Set password to 123',
    'file_not_supported': 'File not supported',
    'only_photo_video_file': 'Only add photos or videos or separate files',
    'only_video': 'Only 1 video can be added',
    'only_file': 'Only 1 file can be added',
    'message_been_deleted': 'Message has been deleted',
    'back_lg': 'Another device has logged in to your account',
    'clear history confirm':
        'Are you sure you want to delete this conversation history?',
    'reset_password_confirm': 'Are you sure you want to reset this password?',
    'unable_send': 'Unable to send',
  };

  static Map chinese = {
    'username': '用户名',
    'password': '密码',
    'welcome': '欢迎来到 ChatAPP',
    'login_content': '立即登录以探索功能并与朋友建立联系。',
    'forgotpass': '忘记密码？',
    'login_error': '登录错误',
    'login': '登录', //登录
    'chatApp': 'ChatApp',
    'my_account': '我的帐户',
    'friend': '朋友',
    'Invite_friend': '添加好友请求',
    'night_mode': '夜间模式',
    'chat_setting': '聊天设置',
    'notification': '通知',
    'language': '语言',
    'log_out': '退出登录',
    'welcome_chat': '欢迎来到 ChatApp',
    'welcome_content': '这个消息应用程序帮助您保护与朋友和组织的隐私权。 与您的朋友和组织开始对话。',
    'create_chat': '创建聊天',
    'pin': '固定',
    'delete_chat': '删除聊天',
    'selct_chat': '选择多个聊天',
    'cancel': '取消',
    'delete': '删除',
    'light_mode': '亮度模式',
    'dark_mode': '暗黑模式',
    'auto_mode': '自动模式',
    'select': '已选择',
    'account': '账户',
    'settings': '设置',
    'chat_delete': '永久删除与之的聊天', //聊天
    'search_chat': '搜索聊天，群组',
    'recent': '最近',
    'clear': '清除', //搜索聊天
    'new_group': '新建群组',
    'friends': '朋友', //创建聊天
    'choose_member': '选择成员',
    'auto_delete_chat': '自动删除消息',
    'off': '关闭',
    'auto_delete_chat_content': '在一段时间后自动删除此组中的每个人的消息',
    'members': '成员',
    'create': '创建',
    'auto_delete_title': '自动删除消息',
    'auto_delete_content': '自动删除已启用以方便您',
    'day': '天',
    'days': '天', //创建群组
    'update_profile': '更新个人资料',
    'update_profile_content': '更新您的个人资料使朋友更容易识别您。',
    'person_information': '个人信息',
    'first_name': '名字',
    'last_name': '姓氏',
    'update': '更新', //更新个人资料
    'search_friend': '寻找朋友',
    'received': '已接收',
    'sent': '已发送',
    'accept': '接受',
    'prieview': '预览',
    'mesage_text_size': '消息文本大小',
    'color_theme': '颜色主题', //聊天设置
    'chat_notification': '聊天通知',
    'notification_content': '有新通知时接收推送通知',
    'translate_mesages': '翻译消息',
    'translate_content': '选择您要将消息翻译成的语言',
    'laguage_systems': '语言系统',
    'language_translate': '语言翻译',
    'language_conttent': '选择您要将消息翻译成的语言', //语言
    'type_a_message': '输入消息...',
    'no_message': '对话中没有消息。',
    'media': '媒体',
    'sharelink': '分享链接',
    'document': '文件',
    'atuto_delete': '自动删除',
    'clear_history': '清除历史记录',
    'leave_group': '离开群组',
    'reply': '回复',
    'copy': '复制',
    'forward': '转发',
    'recall': '撤回',
    'edit': '编辑',
    'multiple_select': '多选',
    'error_name': '名称不能为空',
    'error_message': '消息列表错误通知',
    'error_file': '文件错误通知',
    'error_delete_message': '删除消息错误通知',
    'error_login': '登录错误通知',
    'file_notification': '文件通知',
    'error_image_video': '仅添加单独的图像或视频',
    'error_update': '只能添加1个视频',
    'add_friend_ss': '已成为好友!',
    'no_add_friend': '拒绝添加好友请求!',
    'no_access': '无访问权限',
    'video': '视频',
    'image': '图片',
    'file': '文件',
    'audio': '音频',
    'enter_message': '输入消息',
    'downloading': '下载中...',
    'choose_mode': '选择适合您的模式',
    'delete_message': '消息已删除',
    'group_name': '群组名称',
    'error_api_no_connect': '无法连接到服务器，请再次检查。',
    'unlock_friend': '解锁发送好友请求',
    'translater': '翻译',
    'admin_create': '群组已创建',
    'cancel_friend': '取消好友请求',
    'cancal_friend_with': '取消与好友的请求',
    'cancal_friend_ss': '已取消好友请求',
    'add_friend': '添加好友',
    'leader': '组长',
    'add_member': '添加成员',
    'friend_sent': '好友请求已发送',
    'me': '我',
    'confirm': '确认',
    'delete_group': '删除组',
    'leave_group_confirm': '您确定要离开并删除此群聊吗？',
    'delete_group_confirm': '您确定要删除此群聊吗？',
    'add_account': '添加帐户',
    'you_sure_loguot': '你确定要退出吗？',
    'email': '电子邮件',
    'admin': '管理员',
    'user': '用户',
    'user_name_empty': '用户名不能为空',
    'email_empty': '邮箱不能为空',
    'last_name_empty': '姓氏不能为空',
    'name_empty': '名称不能为空',
    'detail': '详情',
    'select_filter': '选择您要筛选的职称',
    'status': '状态',
    'status_active': '活跃',
    'status_deactive': '已停用',
    'list_account': '账户列表',
    "account_detail": "账户详情",
    'email_format': '电子邮件格式不正确',
    'permission_successively': '权限更改成功',
    'status_successfully': '更改状态成功',
    'lock_account': '锁定账户',
    'unlock_account': '解锁帐户',
    'position': '位置',
    'change_pass': '更改密码',
    'pass_old': '输入旧密码',
    'pass_new': '输入新密码',
    'pass_new_en': '重新输入新密码',
    'pass_validate': '密码必须至少为8个字符！',
    'pass_ss': '密码更改成功！',
    'pass_valiate_distinctive': '新密码必须与旧密码不同！',
    'pass_valiate_overlap': '重新输入的密码与新密码不匹配！',
    'name_ss': '更新成功！',
    'download': '下载',
    'photo_saved_successively': '照片已成功保存到相机胶卷！',
    'photo_saved_error': '将照片保存到照片库时发生错误。',
    'cancel_friend_send': '取消好友请求',
    'is_typing': '正在输入',
    'file_size': '文件大小超过20MB',
    'un_pin': '取消固定',
    'search': '搜索',
    'search_nation': '输入国家名称或国家代码',
    'pinned_message': '固定消息',
    'pin_list': '引脚列表',
    'by': '通过',
    'back_login': '返回登录',
    'dont_account': '没有帐户？ ',
    'sign_up_here': '在这里注册',
    'sign_up': '注册',
    'we_code_phone': '我们已向您发送了电话号码验证码',
    'otp': 'OTP',
    'information_join': '填写加入我们的所有信息',
    'full_name': '全名',
    'enter_password': '再次输入密码',
    'phone_number': '电话号码',
    'continue': '继续',
    'phone_empty': '电话号码不能为空',
    'password_empty': '密码不能为空',
    'confirm_password_empty': '确认密码不能为空',
    'phone_format': '电话号码格式不正确',
    'auto_delete': '自动删除',
    'otp_no_valid': '无效的 OTP',
    'enter_otp': '输入 OTP',
    'phone_no_valid': '无效的电话号码！',
    'forgot_pass': '忘记密码?',
    'forgot_pass_ct': '我们将向您提供的电话号码发送链接。',
    'forgot_pas_phone': '我们已向您的电话号码发送了一个代码',
    'phone': '电话号码',
    'phone_null': '请输入您的电话号码',
    'phone_valid': '无效的电话号码',
    'pass_null': '请输入您的密码！',
    'pass_re_null': '请重新输入您的密码！',
    'pass_reset_ss': '密码重置成功！',
    'resgiter_ss': '账户注册成功！',
    'pass_no_joint': '重新输入的密码不匹配！',
    'last_seen': '最后一次在线',
    'send': '发送',
    'forward_from': '转发自',
    'edited': '已编辑',
    'reset_pass': '重置密码',
    'reset_pass_ss': '将密码设置为123',
    'file_not_supported': '文件不支持',
    'only_photo_video_file': '仅添加照片或视频或单独的文件',
    'only_video': '只能添加1个视频',
    'only_file': '只能添加1个文件',
    'message_been_deleted': '消息已删除',
    'back_lg': '另一设备已登录到您的帐户',
    'clear_history_confirm': '您确定要删除此对话历史记录吗？',
    'reset_password_confirm': '您确定要重置此密码吗？',
    'unable_send': '无法发送',
  };
}
