// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN2MmxdHbk1NbUNt84cYiKG1Z5dbsJU0U',
    appId: '1:655023461374:web:25f83882be0625aa1c66af',
    messagingSenderId: '655023461374',
    projectId: 'chatapp-6b312',
    authDomain: 'chatapp-6b312.firebaseapp.com',
    storageBucket: 'chatapp-6b312.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYvjXc8dfKYulmQrR6Xk6FhQ9MZJUAKIY',
    appId: '1:655023461374:android:73a3b83ad8f818fb1c66af',
    messagingSenderId: '655023461374',
    projectId: 'chatapp-6b312',
    storageBucket: 'chatapp-6b312.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXCZC0zoSHan9kJAjJMPW02XQ2NvYv1eE',
    appId: '1:934688369626:ios:79e1219605d4c81354aee3',
    messagingSenderId: '934688369626',
    projectId: 'chat-app-32084',
    storageBucket: 'chat-app-32084.appspot.com',
    iosBundleId: 'com.chat.pro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBETyUvtfkE-n3NrmD3BqVrCfWbZZTNwT8',
    appId: '1:655023461374:ios:4c383350e6bb2b351c66af',
    messagingSenderId: '934688369626',
    projectId: 'chat-app-32084',
    storageBucket: 'chatapp-6b312.appspot.com',
    iosBundleId: 'com.chat.pro',
  );
}
